CREATE DATABASE BUS_MANAGEMENT_SYSTEM
USE BUS_MANAGEMENT_SYSTEM

CREATE TABLE BUS(
	BUS_ID INT IDENTITY(1,1) PRIMARY KEY,
	BUS_NAME VARCHAR(50) UNIQUE NOT NULL,
	BUS_TYPE VARCHAR(20) NOT NULL,
	SOURCE VARCHAR(50) NOT NULL,	
	DESTINATION VARCHAR(50) NOT NULL,	
	DEPARTURE_LOCATION VARCHAR(50) NOT NULL,
	DEPARTURE_DATE DATE NOT NULL,
	DEPARTURE_TIME TIME NOT NULL,
	ARRIVAL_TIME TIME NOT NULL,
	AVAILABLE_SEAT INT NOT NULL,
	SEAT_NUM INT NOT NULL,
	DRIVER_ID INT  NOT NULL FOREIGN KEY REFERENCES DRIVER(DRIVER_ID),	
	)
	
CREATE TABLE DRIVER(
	DRIVER_ID INT IDENTITY(1,1) PRIMARY KEY,
	DRIVER_NAME VARCHAR(50) NOT NULL,
	DRIVER_ADDRESS VARCHAR(50) NOT NULL,
	DRIVER_PHONE INT UNIQUE NOT NULL,
	)
	
		
CREATE TABLE TICKET(
	TICKET_ID INT IDENTITY(1,1) PRIMARY KEY,
	TICKET_TYPE VARCHAR(20) NULL,  
	TICKET_DATE DATE NOT NULL, 
	TICKET_PRICE VARCHAR(20) NOT NULL,
	BOOKING_TIME TIME NOT NULL,
	BOOKING_SEAT INT NULL,
	TICKET_TIME TIME NOT NULL,
	TOTAL_TICKET INT NOT NULL,
	AVAILABLE_TICKET INT NOT NULL,
	BUS_ID INT NOT NULL FOREIGN KEY REFERENCES BUS(BUS_ID)
	)
	
CREATE TABLE PASSENGER(
	PASSENGER_ID INT IDENTITY(1,1) PRIMARY KEY,
	PASSENGER_NAME VARCHAR(50) NOT NULL,
	PASSENGER_PHONE VARCHAR(20) NOT NULL,
	PASSENGER_EMAIL VARCHAR(50) NOT NULL,
	PASSENGER_ADDRESS VARCHAR(50) NOT NULL,
	TICKET_ID INT NOT NULL FOREIGN KEY REFERENCES TICKET(TICKET_ID),		
	)
	
CREATE TABLE ACCOUNT(
	ACCOUNT_ID INT IDENTITY(1,1) PRIMARY KEY,
	ACCOUNT_EMAIL VARCHAR(50) NOT NULL UNIQUE,
	ACCOUNT_PASSWORD VARCHAR(50) NOT NULL,
	ACCOUNT_TYPE VARCHAR(20) NOT NULL
	)
	
CREATE TABLE ADMIN(
	ADMIN_ID INT IDENTITY(1,1) PRIMARY KEY,
	ADMIN_NAME VARCHAR(50) NOT NULL,
	ADMIN_PHONE VARCHAR(20) NOT NULL,
	ADMIN_EMAIL VARCHAR(20) NOT NULL,
	)
	
CREATE TABLE FEEDBACK(
	FEEDBACK_ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	MESSAGE VARCHAR(500) NOT NULL,
	PASSENGER_ID INT NOT NULL FOREIGN KEY REFERENCES PASSENGER(PASSENGER_ID)
	)
	

INSERT INTO BUS
VALUES('AURNAB PORIBOHON','AC','DHAKA','CHATTOGRAM','RAJARBAGH','2022-07-30','12:41:10','7:20:10','50','50','1')

INSERT INTO DRIVER
VALUES('AURNAB','SHAJANPUR, DHAKA','01521111111')

INSERT INTO FEEDBACK
VALUES('AURNAB','190204009@aust.edu','The seats of the bus is very comfortable','1')

INSERT INTO PASSENGER
VALUES('AURNAB','0153111111','190204009@aust.edu','SHAJAHANPUR, DHAKA','1')

INSERT INTO TICKET
VALUES('AC','2022-7-28','500 TAKA','10:10:10','12','15:12:10','200','20','1')

INSERT INTO ADMIN
VALUES('AURNAB','015211111','190204009@aust.edu')

INSERT INTO ACCOUNT
VALUES('190204009@aust.edu','123456789','ADMIN')

	

	
