/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication78.pkgfor.project.cse3104;

/**
 *
 * @author User
 */
public class showtable extends javax.swing.JFrame {

    /**
     * Creates new form showtable
     */
    public showtable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonbus = new javax.swing.JButton();
        jButtondriver = new javax.swing.JButton();
        jButtonpassenger = new javax.swing.JButton();
        jButtonadmin = new javax.swing.JButton();
        jButtonticet = new javax.swing.JButton();
        jButtonfeedback = new javax.swing.JButton();
        jButtonback = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonbus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonbus.setText("BUS");
        jButtonbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbusActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 152, 42));

        jButtondriver.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtondriver.setText("DRIVER");
        jButtondriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondriverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtondriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 165, 40));

        jButtonpassenger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonpassenger.setText("PASSENGER");
        jButtonpassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpassengerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonpassenger, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 174, 42));

        jButtonadmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonadmin.setText("ADMIN");
        jButtonadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonadminActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 274, 152, 44));

        jButtonticet.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonticet.setText("TICKET");
        jButtonticet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonticetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonticet, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 274, 165, 44));

        jButtonfeedback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonfeedback.setText("FEEDBACK");
        jButtonfeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfeedbackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonfeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 274, 174, 44));

        jButtonback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonback.setText("BACK");
        jButtonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonback, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 378, 152, 43));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Driver info by Bus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 230, 40));

        jLabel1.setBackground(new java.awt.Color(0, 102, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("WELLCOME TO OUR BUS MANAGEMENT SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 440, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\database project\\images (1).jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 160));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\database project\\images (5).jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 270, 160));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\database project\\360_F_236054283_lLtDimkzpyRlnPxUEb9tSE4EWnhL7SOi.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 320, 160));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\database project\\table.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 850, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbackActionPerformed
        // TODO add your handling code here:
        LogIn obj = new LogIn();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonbackActionPerformed

    private void jButtonbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbusActionPerformed
        // TODO add your handling code here:
        InsertBus obj = new InsertBus();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonbusActionPerformed

    private void jButtondriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondriverActionPerformed
        // TODO add your handling code here:
        insertDriver obj = new insertDriver();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtondriverActionPerformed

    private void jButtonpassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpassengerActionPerformed
        // TODO add your handling code here:
        InsertPassenger obj = new InsertPassenger();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonpassengerActionPerformed

    private void jButtonadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonadminActionPerformed
        // TODO add your handling code here:
        InsertAdmin obj = new InsertAdmin();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonadminActionPerformed

    private void jButtonticetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonticetActionPerformed
        // TODO add your handling code here:
        iNSERTTICKET obj = new iNSERTTICKET();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonticetActionPerformed

    private void jButtonfeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfeedbackActionPerformed
        // TODO add your handling code here:
        InsertFeedback obj = new InsertFeedback();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonfeedbackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Join obj = new Join();
        obj.setVisible(true);
//        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showtable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showtable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showtable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showtable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showtable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonadmin;
    private javax.swing.JButton jButtonback;
    private javax.swing.JButton jButtonbus;
    private javax.swing.JButton jButtondriver;
    private javax.swing.JButton jButtonfeedback;
    private javax.swing.JButton jButtonpassenger;
    private javax.swing.JButton jButtonticet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
